kind: Service
apiVersion: v1
metadata:
  name: hello-world-service
spec:
  selector:
    app: demo-app
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 31080
  type: NodePort
